[package]
name = "nlbundler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
regex = "1.11.1"
thiserror = "2.0.11"
walkdir = "2.5.0"
